//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: person.proto
//
//package flinkbase.typeinfo.model;
//
//public final class PersonMessage {
//  private PersonMessage() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  /**
//   * Protobuf enum {@code Gender}
//   */
//  public enum Gender
//      implements com.google.protobuf.ProtocolMessageEnum {
//    /**
//     * <code>male = 0;</code>
//     */
//    male(0),
//    /**
//     * <code>female = 1;</code>
//     */
//    female(1),
//    UNRECOGNIZED(-1),
//    ;
//
//    /**
//     * <code>male = 0;</code>
//     */
//    public static final int male_VALUE = 0;
//    /**
//     * <code>female = 1;</code>
//     */
//    public static final int female_VALUE = 1;
//
//
//    public final int getNumber() {
//      if (this == UNRECOGNIZED) {
//        throw new java.lang.IllegalArgumentException(
//            "Can't get the number of an unknown enum value.");
//      }
//      return value;
//    }
//
//    /**
//     * @param value The numeric wire value of the corresponding enum entry.
//     * @return The enum associated with the given numeric wire value.
//     * @deprecated Use {@link #forNumber(int)} instead.
//     */
//    @java.lang.Deprecated
//    public static Gender valueOf(int value) {
//      return forNumber(value);
//    }
//
//    /**
//     * @param value The numeric wire value of the corresponding enum entry.
//     * @return The enum associated with the given numeric wire value.
//     */
//    public static Gender forNumber(int value) {
//      switch (value) {
//        case 0: return male;
//        case 1: return female;
//        default: return null;
//      }
//    }
//
//    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
//        internalGetValueMap() {
//      return internalValueMap;
//    }
//    private static final com.google.protobuf.Internal.EnumLiteMap<
//        Gender> internalValueMap =
//          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
//            public Gender findValueByNumber(int number) {
//              return Gender.forNumber(number);
//            }
//          };
//
//    public final com.google.protobuf.Descriptors.EnumValueDescriptor
//        getValueDescriptor() {
//      if (this == UNRECOGNIZED) {
//        throw new java.lang.IllegalStateException(
//            "Can't get the descriptor of an unrecognized enum value.");
//      }
//      return getDescriptor().getValues().get(ordinal());
//    }
//    public final com.google.protobuf.Descriptors.EnumDescriptor
//        getDescriptorForType() {
//      return getDescriptor();
//    }
//    public static final com.google.protobuf.Descriptors.EnumDescriptor
//        getDescriptor() {
//      return PersonMessage.getDescriptor().getEnumTypes().get(0);
//    }
//
//    private static final Gender[] VALUES = values();
//
//    public static Gender valueOf(
//        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
//      if (desc.getType() != getDescriptor()) {
//        throw new java.lang.IllegalArgumentException(
//          "EnumValueDescriptor is not for this type.");
//      }
//      if (desc.getIndex() == -1) {
//        return UNRECOGNIZED;
//      }
//      return VALUES[desc.getIndex()];
//    }
//
//    private final int value;
//
//    private Gender(int value) {
//      this.value = value;
//    }
//
//    // @@protoc_insertion_point(enum_scope:Gender)
//  }
//
//  public interface PersonModelOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:PersonModel)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>int32 id = 1;</code>
//     * @return The id.
//     */
//    int getId();
//
//    /**
//     * <code>string name = 2;</code>
//     * @return The name.
//     */
//    java.lang.String getName();
//    /**
//     * <code>string name = 2;</code>
//     * @return The bytes for name.
//     */
//    com.google.protobuf.ByteString
//        getNameBytes();
//
//    /**
//     * <code>string emil = 3;</code>
//     * @return The emil.
//     */
//    java.lang.String getEmil();
//    /**
//     * <code>string emil = 3;</code>
//     * @return The bytes for emil.
//     */
//    com.google.protobuf.ByteString
//        getEmilBytes();
//
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    java.util.List<PersonMessage.PersonModel.PersonAddress>
//        getAddressesList();
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    PersonMessage.PersonModel.PersonAddress getAddresses(int index);
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    int getAddressesCount();
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    java.util.List<? extends PersonMessage.PersonModel.PersonAddressOrBuilder>
//        getAddressesOrBuilderList();
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    PersonMessage.PersonModel.PersonAddressOrBuilder getAddressesOrBuilder(
//        int index);
//
//    /**
//     * <code>.Gender gender = 5;</code>
//     * @return The enum numeric value on the wire for gender.
//     */
//    int getGenderValue();
//    /**
//     * <code>.Gender gender = 5;</code>
//     * @return The gender.
//     */
//    PersonMessage.Gender getGender();
//  }
//  /**
//   * <pre>
//   * https://developers.google.cn/protocol-buffers/docs/proto3
//   * </pre>
//   *
//   * Protobuf type {@code PersonModel}
//   */
//  public static final class PersonModel extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:PersonModel)
//      PersonModelOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use PersonModel.newBuilder() to construct.
//    private PersonModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private PersonModel() {
//      name_ = "";
//      emil_ = "";
//      addresses_ = java.util.Collections.emptyList();
//      gender_ = 0;
//    }
//
//    @java.lang.Override
//    @SuppressWarnings({"unused"})
//    protected java.lang.Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new PersonModel();
//    }
//
//    @java.lang.Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private PersonModel(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new java.lang.NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            case 8: {
//
//              id_ = input.readInt32();
//              break;
//            }
//            case 18: {
//              java.lang.String s = input.readStringRequireUtf8();
//
//              name_ = s;
//              break;
//            }
//            case 26: {
//              java.lang.String s = input.readStringRequireUtf8();
//
//              emil_ = s;
//              break;
//            }
//            case 34: {
//              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
//                addresses_ = new java.util.ArrayList<PersonMessage.PersonModel.PersonAddress>();
//                mutable_bitField0_ |= 0x00000001;
//              }
//              addresses_.add(
//                  input.readMessage(PersonMessage.PersonModel.PersonAddress.parser(), extensionRegistry));
//              break;
//            }
//            case 40: {
//              int rawValue = input.readEnum();
//
//              gender_ = rawValue;
//              break;
//            }
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        if (((mutable_bitField0_ & 0x00000001) != 0)) {
//          addresses_ = java.util.Collections.unmodifiableList(addresses_);
//        }
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return PersonMessage.internal_static_PersonModel_descriptor;
//    }
//
//    @java.lang.Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return PersonMessage.internal_static_PersonModel_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              PersonMessage.PersonModel.class, PersonMessage.PersonModel.Builder.class);
//    }
//
//    public interface PersonAddressOrBuilder extends
//        // @@protoc_insertion_point(interface_extends:PersonModel.PersonAddress)
//        com.google.protobuf.MessageOrBuilder {
//
//      /**
//       * <code>int32 id = 1;</code>
//       * @return The id.
//       */
//      int getId();
//
//      /**
//       * <code>string name = 2;</code>
//       * @return The name.
//       */
//      java.lang.String getName();
//      /**
//       * <code>string name = 2;</code>
//       * @return The bytes for name.
//       */
//      com.google.protobuf.ByteString
//          getNameBytes();
//    }
//    /**
//     * Protobuf type {@code PersonModel.PersonAddress}
//     */
//    public static final class PersonAddress extends
//        com.google.protobuf.GeneratedMessageV3 implements
//        // @@protoc_insertion_point(message_implements:PersonModel.PersonAddress)
//        PersonAddressOrBuilder {
//    private static final long serialVersionUID = 0L;
//      // Use PersonAddress.newBuilder() to construct.
//      private PersonAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//        super(builder);
//      }
//      private PersonAddress() {
//        name_ = "";
//      }
//
//      @java.lang.Override
//      @SuppressWarnings({"unused"})
//      protected java.lang.Object newInstance(
//          UnusedPrivateParameter unused) {
//        return new PersonAddress();
//      }
//
//      @java.lang.Override
//      public final com.google.protobuf.UnknownFieldSet
//      getUnknownFields() {
//        return this.unknownFields;
//      }
//      private PersonAddress(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        this();
//        if (extensionRegistry == null) {
//          throw new java.lang.NullPointerException();
//        }
//        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//            com.google.protobuf.UnknownFieldSet.newBuilder();
//        try {
//          boolean done = false;
//          while (!done) {
//            int tag = input.readTag();
//            switch (tag) {
//              case 0:
//                done = true;
//                break;
//              case 8: {
//
//                id_ = input.readInt32();
//                break;
//              }
//              case 18: {
//                java.lang.String s = input.readStringRequireUtf8();
//
//                name_ = s;
//                break;
//              }
//              default: {
//                if (!parseUnknownField(
//                    input, unknownFields, extensionRegistry, tag)) {
//                  done = true;
//                }
//                break;
//              }
//            }
//          }
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          throw e.setUnfinishedMessage(this);
//        } catch (java.io.IOException e) {
//          throw new com.google.protobuf.InvalidProtocolBufferException(
//              e).setUnfinishedMessage(this);
//        } finally {
//          this.unknownFields = unknownFields.build();
//          makeExtensionsImmutable();
//        }
//      }
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return PersonMessage.internal_static_PersonModel_PersonAddress_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return PersonMessage.internal_static_PersonModel_PersonAddress_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                PersonMessage.PersonModel.PersonAddress.class, PersonMessage.PersonModel.PersonAddress.Builder.class);
//      }
//
//      public static final int ID_FIELD_NUMBER = 1;
//      private int id_;
//      /**
//       * <code>int32 id = 1;</code>
//       * @return The id.
//       */
//      @java.lang.Override
//      public int getId() {
//        return id_;
//      }
//
//      public static final int NAME_FIELD_NUMBER = 2;
//      private volatile java.lang.Object name_;
//      /**
//       * <code>string name = 2;</code>
//       * @return The name.
//       */
//      @java.lang.Override
//      public java.lang.String getName() {
//        java.lang.Object ref = name_;
//        if (ref instanceof java.lang.String) {
//          return (java.lang.String) ref;
//        } else {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          name_ = s;
//          return s;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return The bytes for name.
//       */
//      @java.lang.Override
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        java.lang.Object ref = name_;
//        if (ref instanceof java.lang.String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//
//      private byte memoizedIsInitialized = -1;
//      @java.lang.Override
//      public final boolean isInitialized() {
//        byte isInitialized = memoizedIsInitialized;
//        if (isInitialized == 1) return true;
//        if (isInitialized == 0) return false;
//
//        memoizedIsInitialized = 1;
//        return true;
//      }
//
//      @java.lang.Override
//      public void writeTo(com.google.protobuf.CodedOutputStream output)
//                          throws java.io.IOException {
//        if (id_ != 0) {
//          output.writeInt32(1, id_);
//        }
//        if (!getNameBytes().isEmpty()) {
//          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
//        }
//        unknownFields.writeTo(output);
//      }
//
//      @java.lang.Override
//      public int getSerializedSize() {
//        int size = memoizedSize;
//        if (size != -1) return size;
//
//        size = 0;
//        if (id_ != 0) {
//          size += com.google.protobuf.CodedOutputStream
//            .computeInt32Size(1, id_);
//        }
//        if (!getNameBytes().isEmpty()) {
//          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
//        }
//        size += unknownFields.getSerializedSize();
//        memoizedSize = size;
//        return size;
//      }
//
//      @java.lang.Override
//      public boolean equals(final java.lang.Object obj) {
//        if (obj == this) {
//         return true;
//        }
//        if (!(obj instanceof PersonMessage.PersonModel.PersonAddress)) {
//          return super.equals(obj);
//        }
//        PersonMessage.PersonModel.PersonAddress other = (PersonMessage.PersonModel.PersonAddress) obj;
//
//        if (getId()
//            != other.getId()) return false;
//        if (!getName()
//            .equals(other.getName())) return false;
//        if (!unknownFields.equals(other.unknownFields)) return false;
//        return true;
//      }
//
//      @java.lang.Override
//      public int hashCode() {
//        if (memoizedHashCode != 0) {
//          return memoizedHashCode;
//        }
//        int hash = 41;
//        hash = (19 * hash) + getDescriptor().hashCode();
//        hash = (37 * hash) + ID_FIELD_NUMBER;
//        hash = (53 * hash) + getId();
//        hash = (37 * hash) + NAME_FIELD_NUMBER;
//        hash = (53 * hash) + getName().hashCode();
//        hash = (29 * hash) + unknownFields.hashCode();
//        memoizedHashCode = hash;
//        return hash;
//      }
//
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          java.nio.ByteBuffer data)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          java.nio.ByteBuffer data,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data, extensionRegistry);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          com.google.protobuf.ByteString data)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          com.google.protobuf.ByteString data,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data, extensionRegistry);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(byte[] data)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          byte[] data,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return PARSER.parseFrom(data, extensionRegistry);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(java.io.InputStream input)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          java.io.InputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input, extensionRegistry);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseDelimitedFrom(java.io.InputStream input)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseDelimitedWithIOException(PARSER, input);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseDelimitedFrom(
//          java.io.InputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          com.google.protobuf.CodedInputStream input)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input);
//      }
//      public static PersonMessage.PersonModel.PersonAddress parseFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        return com.google.protobuf.GeneratedMessageV3
//            .parseWithIOException(PARSER, input, extensionRegistry);
//      }
//
//      @java.lang.Override
//      public Builder newBuilderForType() { return newBuilder(); }
//      public static Builder newBuilder() {
//        return DEFAULT_INSTANCE.toBuilder();
//      }
//      public static Builder newBuilder(PersonMessage.PersonModel.PersonAddress prototype) {
//        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//      }
//      @java.lang.Override
//      public Builder toBuilder() {
//        return this == DEFAULT_INSTANCE
//            ? new Builder() : new Builder().mergeFrom(this);
//      }
//
//      @java.lang.Override
//      protected Builder newBuilderForType(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        Builder builder = new Builder(parent);
//        return builder;
//      }
//      /**
//       * Protobuf type {@code PersonModel.PersonAddress}
//       */
//      public static final class Builder extends
//          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//          // @@protoc_insertion_point(builder_implements:PersonModel.PersonAddress)
//          PersonMessage.PersonModel.PersonAddressOrBuilder {
//        public static final com.google.protobuf.Descriptors.Descriptor
//            getDescriptor() {
//          return PersonMessage.internal_static_PersonModel_PersonAddress_descriptor;
//        }
//
//        @java.lang.Override
//        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//            internalGetFieldAccessorTable() {
//          return PersonMessage.internal_static_PersonModel_PersonAddress_fieldAccessorTable
//              .ensureFieldAccessorsInitialized(
//                  PersonMessage.PersonModel.PersonAddress.class, PersonMessage.PersonModel.PersonAddress.Builder.class);
//        }
//
//        // Construct using fink02.stream.typeinfo.model.PersonMessage.PersonModel.PersonAddress.newBuilder()
//        private Builder() {
//          maybeForceBuilderInitialization();
//        }
//
//        private Builder(
//            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//          super(parent);
//          maybeForceBuilderInitialization();
//        }
//        private void maybeForceBuilderInitialization() {
//          if (com.google.protobuf.GeneratedMessageV3
//                  .alwaysUseFieldBuilders) {
//          }
//        }
//        @java.lang.Override
//        public Builder clear() {
//          super.clear();
//          id_ = 0;
//
//          name_ = "";
//
//          return this;
//        }
//
//        @java.lang.Override
//        public com.google.protobuf.Descriptors.Descriptor
//            getDescriptorForType() {
//          return PersonMessage.internal_static_PersonModel_PersonAddress_descriptor;
//        }
//
//        @java.lang.Override
//        public PersonMessage.PersonModel.PersonAddress getDefaultInstanceForType() {
//          return PersonMessage.PersonModel.PersonAddress.getDefaultInstance();
//        }
//
//        @java.lang.Override
//        public PersonMessage.PersonModel.PersonAddress build() {
//          PersonMessage.PersonModel.PersonAddress result = buildPartial();
//          if (!result.isInitialized()) {
//            throw newUninitializedMessageException(result);
//          }
//          return result;
//        }
//
//        @java.lang.Override
//        public PersonMessage.PersonModel.PersonAddress buildPartial() {
//          PersonMessage.PersonModel.PersonAddress result = new PersonMessage.PersonModel.PersonAddress(this);
//          result.id_ = id_;
//          result.name_ = name_;
//          onBuilt();
//          return result;
//        }
//
//        @java.lang.Override
//        public Builder clone() {
//          return super.clone();
//        }
//        @java.lang.Override
//        public Builder setField(
//            com.google.protobuf.Descriptors.FieldDescriptor field,
//            java.lang.Object value) {
//          return super.setField(field, value);
//        }
//        @java.lang.Override
//        public Builder clearField(
//            com.google.protobuf.Descriptors.FieldDescriptor field) {
//          return super.clearField(field);
//        }
//        @java.lang.Override
//        public Builder clearOneof(
//            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//          return super.clearOneof(oneof);
//        }
//        @java.lang.Override
//        public Builder setRepeatedField(
//            com.google.protobuf.Descriptors.FieldDescriptor field,
//            int index, java.lang.Object value) {
//          return super.setRepeatedField(field, index, value);
//        }
//        @java.lang.Override
//        public Builder addRepeatedField(
//            com.google.protobuf.Descriptors.FieldDescriptor field,
//            java.lang.Object value) {
//          return super.addRepeatedField(field, value);
//        }
//        @java.lang.Override
//        public Builder mergeFrom(com.google.protobuf.Message other) {
//          if (other instanceof PersonMessage.PersonModel.PersonAddress) {
//            return mergeFrom((PersonMessage.PersonModel.PersonAddress)other);
//          } else {
//            super.mergeFrom(other);
//            return this;
//          }
//        }
//
//        public Builder mergeFrom(PersonMessage.PersonModel.PersonAddress other) {
//          if (other == PersonMessage.PersonModel.PersonAddress.getDefaultInstance()) return this;
//          if (other.getId() != 0) {
//            setId(other.getId());
//          }
//          if (!other.getName().isEmpty()) {
//            name_ = other.name_;
//            onChanged();
//          }
//          this.mergeUnknownFields(other.unknownFields);
//          onChanged();
//          return this;
//        }
//
//        @java.lang.Override
//        public final boolean isInitialized() {
//          return true;
//        }
//
//        @java.lang.Override
//        public Builder mergeFrom(
//            com.google.protobuf.CodedInputStream input,
//            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//            throws java.io.IOException {
//          PersonMessage.PersonModel.PersonAddress parsedMessage = null;
//          try {
//            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//            parsedMessage = (PersonMessage.PersonModel.PersonAddress) e.getUnfinishedMessage();
//            throw e.unwrapIOException();
//          } finally {
//            if (parsedMessage != null) {
//              mergeFrom(parsedMessage);
//            }
//          }
//          return this;
//        }
//
//        private int id_ ;
//        /**
//         * <code>int32 id = 1;</code>
//         * @return The id.
//         */
//        @java.lang.Override
//        public int getId() {
//          return id_;
//        }
//        /**
//         * <code>int32 id = 1;</code>
//         * @param value The id to set.
//         * @return This builder for chaining.
//         */
//        public Builder setId(int value) {
//
//          id_ = value;
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>int32 id = 1;</code>
//         * @return This builder for chaining.
//         */
//        public Builder clearId() {
//
//          id_ = 0;
//          onChanged();
//          return this;
//        }
//
//        private java.lang.Object name_ = "";
//        /**
//         * <code>string name = 2;</code>
//         * @return The name.
//         */
//        public java.lang.String getName() {
//          java.lang.Object ref = name_;
//          if (!(ref instanceof java.lang.String)) {
//            com.google.protobuf.ByteString bs =
//                (com.google.protobuf.ByteString) ref;
//            java.lang.String s = bs.toStringUtf8();
//            name_ = s;
//            return s;
//          } else {
//            return (java.lang.String) ref;
//          }
//        }
//        /**
//         * <code>string name = 2;</code>
//         * @return The bytes for name.
//         */
//        public com.google.protobuf.ByteString
//            getNameBytes() {
//          java.lang.Object ref = name_;
//          if (ref instanceof String) {
//            com.google.protobuf.ByteString b =
//                com.google.protobuf.ByteString.copyFromUtf8(
//                    (java.lang.String) ref);
//            name_ = b;
//            return b;
//          } else {
//            return (com.google.protobuf.ByteString) ref;
//          }
//        }
//        /**
//         * <code>string name = 2;</code>
//         * @param value The name to set.
//         * @return This builder for chaining.
//         */
//        public Builder setName(
//            java.lang.String value) {
//          if (value == null) {
//    throw new NullPointerException();
//  }
//
//          name_ = value;
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>string name = 2;</code>
//         * @return This builder for chaining.
//         */
//        public Builder clearName() {
//
//          name_ = getDefaultInstance().getName();
//          onChanged();
//          return this;
//        }
//        /**
//         * <code>string name = 2;</code>
//         * @param value The bytes for name to set.
//         * @return This builder for chaining.
//         */
//        public Builder setNameBytes(
//            com.google.protobuf.ByteString value) {
//          if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//          name_ = value;
//          onChanged();
//          return this;
//        }
//        @java.lang.Override
//        public final Builder setUnknownFields(
//            final com.google.protobuf.UnknownFieldSet unknownFields) {
//          return super.setUnknownFields(unknownFields);
//        }
//
//        @java.lang.Override
//        public final Builder mergeUnknownFields(
//            final com.google.protobuf.UnknownFieldSet unknownFields) {
//          return super.mergeUnknownFields(unknownFields);
//        }
//
//
//        // @@protoc_insertion_point(builder_scope:PersonModel.PersonAddress)
//      }
//
//      // @@protoc_insertion_point(class_scope:PersonModel.PersonAddress)
//      private static final PersonMessage.PersonModel.PersonAddress DEFAULT_INSTANCE;
//      static {
//        DEFAULT_INSTANCE = new PersonMessage.PersonModel.PersonAddress();
//      }
//
//      public static PersonMessage.PersonModel.PersonAddress getDefaultInstance() {
//        return DEFAULT_INSTANCE;
//      }
//
//      private static final com.google.protobuf.Parser<PersonAddress>
//          PARSER = new com.google.protobuf.AbstractParser<PersonAddress>() {
//        @java.lang.Override
//        public PersonAddress parsePartialFrom(
//            com.google.protobuf.CodedInputStream input,
//            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//            throws com.google.protobuf.InvalidProtocolBufferException {
//          return new PersonAddress(input, extensionRegistry);
//        }
//      };
//
//      public static com.google.protobuf.Parser<PersonAddress> parser() {
//        return PARSER;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Parser<PersonAddress> getParserForType() {
//        return PARSER;
//      }
//
//      @java.lang.Override
//      public PersonMessage.PersonModel.PersonAddress getDefaultInstanceForType() {
//        return DEFAULT_INSTANCE;
//      }
//
//    }
//
//    public static final int ID_FIELD_NUMBER = 1;
//    private int id_;
//    /**
//     * <code>int32 id = 1;</code>
//     * @return The id.
//     */
//    @java.lang.Override
//    public int getId() {
//      return id_;
//    }
//
//    public static final int NAME_FIELD_NUMBER = 2;
//    private volatile java.lang.Object name_;
//    /**
//     * <code>string name = 2;</code>
//     * @return The name.
//     */
//    @java.lang.Override
//    public java.lang.String getName() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        name_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string name = 2;</code>
//     * @return The bytes for name.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getNameBytes() {
//      java.lang.Object ref = name_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        name_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int EMIL_FIELD_NUMBER = 3;
//    private volatile java.lang.Object emil_;
//    /**
//     * <code>string emil = 3;</code>
//     * @return The emil.
//     */
//    @java.lang.Override
//    public java.lang.String getEmil() {
//      java.lang.Object ref = emil_;
//      if (ref instanceof java.lang.String) {
//        return (java.lang.String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        java.lang.String s = bs.toStringUtf8();
//        emil_ = s;
//        return s;
//      }
//    }
//    /**
//     * <code>string emil = 3;</code>
//     * @return The bytes for emil.
//     */
//    @java.lang.Override
//    public com.google.protobuf.ByteString
//        getEmilBytes() {
//      java.lang.Object ref = emil_;
//      if (ref instanceof java.lang.String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (java.lang.String) ref);
//        emil_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    public static final int ADDRESSES_FIELD_NUMBER = 4;
//    private java.util.List<PersonMessage.PersonModel.PersonAddress> addresses_;
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    @java.lang.Override
//    public java.util.List<PersonMessage.PersonModel.PersonAddress> getAddressesList() {
//      return addresses_;
//    }
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    @java.lang.Override
//    public java.util.List<? extends PersonMessage.PersonModel.PersonAddressOrBuilder>
//        getAddressesOrBuilderList() {
//      return addresses_;
//    }
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    @java.lang.Override
//    public int getAddressesCount() {
//      return addresses_.size();
//    }
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    @java.lang.Override
//    public PersonMessage.PersonModel.PersonAddress getAddresses(int index) {
//      return addresses_.get(index);
//    }
//    /**
//     * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//     */
//    @java.lang.Override
//    public PersonMessage.PersonModel.PersonAddressOrBuilder getAddressesOrBuilder(
//        int index) {
//      return addresses_.get(index);
//    }
//
//    public static final int GENDER_FIELD_NUMBER = 5;
//    private int gender_;
//    /**
//     * <code>.Gender gender = 5;</code>
//     * @return The enum numeric value on the wire for gender.
//     */
//    @java.lang.Override public int getGenderValue() {
//      return gender_;
//    }
//    /**
//     * <code>.Gender gender = 5;</code>
//     * @return The gender.
//     */
//    @java.lang.Override public PersonMessage.Gender getGender() {
//      @SuppressWarnings("deprecation")
//      PersonMessage.Gender result = PersonMessage.Gender.valueOf(gender_);
//      return result == null ? PersonMessage.Gender.UNRECOGNIZED : result;
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @java.lang.Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @java.lang.Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (id_ != 0) {
//        output.writeInt32(1, id_);
//      }
//      if (!getNameBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
//      }
//      if (!getEmilBytes().isEmpty()) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emil_);
//      }
//      for (int i = 0; i < addresses_.size(); i++) {
//        output.writeMessage(4, addresses_.get(i));
//      }
//      if (gender_ != PersonMessage.Gender.male.getNumber()) {
//        output.writeEnum(5, gender_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    @java.lang.Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (id_ != 0) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(1, id_);
//      }
//      if (!getNameBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
//      }
//      if (!getEmilBytes().isEmpty()) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, emil_);
//      }
//      for (int i = 0; i < addresses_.size(); i++) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeMessageSize(4, addresses_.get(i));
//      }
//      if (gender_ != PersonMessage.Gender.male.getNumber()) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeEnumSize(5, gender_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @java.lang.Override
//    public boolean equals(final java.lang.Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof PersonMessage.PersonModel)) {
//        return super.equals(obj);
//      }
//      PersonMessage.PersonModel other = (PersonMessage.PersonModel) obj;
//
//      if (getId()
//          != other.getId()) return false;
//      if (!getName()
//          .equals(other.getName())) return false;
//      if (!getEmil()
//          .equals(other.getEmil())) return false;
//      if (!getAddressesList()
//          .equals(other.getAddressesList())) return false;
//      if (gender_ != other.gender_) return false;
//      if (!unknownFields.equals(other.unknownFields)) return false;
//      return true;
//    }
//
//    @java.lang.Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      hash = (37 * hash) + ID_FIELD_NUMBER;
//      hash = (53 * hash) + getId();
//      hash = (37 * hash) + NAME_FIELD_NUMBER;
//      hash = (53 * hash) + getName().hashCode();
//      hash = (37 * hash) + EMIL_FIELD_NUMBER;
//      hash = (53 * hash) + getEmil().hashCode();
//      if (getAddressesCount() > 0) {
//        hash = (37 * hash) + ADDRESSES_FIELD_NUMBER;
//        hash = (53 * hash) + getAddressesList().hashCode();
//      }
//      hash = (37 * hash) + GENDER_FIELD_NUMBER;
//      hash = (53 * hash) + gender_;
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static PersonMessage.PersonModel parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static PersonMessage.PersonModel parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static PersonMessage.PersonModel parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static PersonMessage.PersonModel parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static PersonMessage.PersonModel parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static PersonMessage.PersonModel parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @java.lang.Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(PersonMessage.PersonModel prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @java.lang.Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @java.lang.Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * <pre>
//     * https://developers.google.cn/protocol-buffers/docs/proto3
//     * </pre>
//     *
//     * Protobuf type {@code PersonModel}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:PersonModel)
//        PersonMessage.PersonModelOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return PersonMessage.internal_static_PersonModel_descriptor;
//      }
//
//      @java.lang.Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return PersonMessage.internal_static_PersonModel_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                PersonMessage.PersonModel.class, PersonMessage.PersonModel.Builder.class);
//      }
//
//      // Construct using fink02.stream.typeinfo.model.PersonMessage.PersonModel.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//          getAddressesFieldBuilder();
//        }
//      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        id_ = 0;
//
//        name_ = "";
//
//        emil_ = "";
//
//        if (addressesBuilder_ == null) {
//          addresses_ = java.util.Collections.emptyList();
//          bitField0_ = (bitField0_ & ~0x00000001);
//        } else {
//          addressesBuilder_.clear();
//        }
//        gender_ = 0;
//
//        return this;
//      }
//
//      @java.lang.Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return PersonMessage.internal_static_PersonModel_descriptor;
//      }
//
//      @java.lang.Override
//      public PersonMessage.PersonModel getDefaultInstanceForType() {
//        return PersonMessage.PersonModel.getDefaultInstance();
//      }
//
//      @java.lang.Override
//      public PersonMessage.PersonModel build() {
//        PersonMessage.PersonModel result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @java.lang.Override
//      public PersonMessage.PersonModel buildPartial() {
//        PersonMessage.PersonModel result = new PersonMessage.PersonModel(this);
//        int from_bitField0_ = bitField0_;
//        result.id_ = id_;
//        result.name_ = name_;
//        result.emil_ = emil_;
//        if (addressesBuilder_ == null) {
//          if (((bitField0_ & 0x00000001) != 0)) {
//            addresses_ = java.util.Collections.unmodifiableList(addresses_);
//            bitField0_ = (bitField0_ & ~0x00000001);
//          }
//          result.addresses_ = addresses_;
//        } else {
//          result.addresses_ = addressesBuilder_.build();
//        }
//        result.gender_ = gender_;
//        onBuilt();
//        return result;
//      }
//
//      @java.lang.Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @java.lang.Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.setField(field, value);
//      }
//      @java.lang.Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @java.lang.Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @java.lang.Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, java.lang.Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @java.lang.Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          java.lang.Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @java.lang.Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof PersonMessage.PersonModel) {
//          return mergeFrom((PersonMessage.PersonModel)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(PersonMessage.PersonModel other) {
//        if (other == PersonMessage.PersonModel.getDefaultInstance()) return this;
//        if (other.getId() != 0) {
//          setId(other.getId());
//        }
//        if (!other.getName().isEmpty()) {
//          name_ = other.name_;
//          onChanged();
//        }
//        if (!other.getEmil().isEmpty()) {
//          emil_ = other.emil_;
//          onChanged();
//        }
//        if (addressesBuilder_ == null) {
//          if (!other.addresses_.isEmpty()) {
//            if (addresses_.isEmpty()) {
//              addresses_ = other.addresses_;
//              bitField0_ = (bitField0_ & ~0x00000001);
//            } else {
//              ensureAddressesIsMutable();
//              addresses_.addAll(other.addresses_);
//            }
//            onChanged();
//          }
//        } else {
//          if (!other.addresses_.isEmpty()) {
//            if (addressesBuilder_.isEmpty()) {
//              addressesBuilder_.dispose();
//              addressesBuilder_ = null;
//              addresses_ = other.addresses_;
//              bitField0_ = (bitField0_ & ~0x00000001);
//              addressesBuilder_ =
//                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
//                   getAddressesFieldBuilder() : null;
//            } else {
//              addressesBuilder_.addAllMessages(other.addresses_);
//            }
//          }
//        }
//        if (other.gender_ != 0) {
//          setGenderValue(other.getGenderValue());
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      @java.lang.Override
//      public final boolean isInitialized() {
//        return true;
//      }
//
//      @java.lang.Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        PersonMessage.PersonModel parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (PersonMessage.PersonModel) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private int id_ ;
//      /**
//       * <code>int32 id = 1;</code>
//       * @return The id.
//       */
//      @java.lang.Override
//      public int getId() {
//        return id_;
//      }
//      /**
//       * <code>int32 id = 1;</code>
//       * @param value The id to set.
//       * @return This builder for chaining.
//       */
//      public Builder setId(int value) {
//
//        id_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>int32 id = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearId() {
//
//        id_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object name_ = "";
//      /**
//       * <code>string name = 2;</code>
//       * @return The name.
//       */
//      public java.lang.String getName() {
//        java.lang.Object ref = name_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          name_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return The bytes for name.
//       */
//      public com.google.protobuf.ByteString
//          getNameBytes() {
//        java.lang.Object ref = name_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          name_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @param value The name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setName(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        name_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearName() {
//
//        name_ = getDefaultInstance().getName();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string name = 2;</code>
//       * @param value The bytes for name to set.
//       * @return This builder for chaining.
//       */
//      public Builder setNameBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        name_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.lang.Object emil_ = "";
//      /**
//       * <code>string emil = 3;</code>
//       * @return The emil.
//       */
//      public java.lang.String getEmil() {
//        java.lang.Object ref = emil_;
//        if (!(ref instanceof java.lang.String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          java.lang.String s = bs.toStringUtf8();
//          emil_ = s;
//          return s;
//        } else {
//          return (java.lang.String) ref;
//        }
//      }
//      /**
//       * <code>string emil = 3;</code>
//       * @return The bytes for emil.
//       */
//      public com.google.protobuf.ByteString
//          getEmilBytes() {
//        java.lang.Object ref = emil_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (java.lang.String) ref);
//          emil_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>string emil = 3;</code>
//       * @param value The emil to set.
//       * @return This builder for chaining.
//       */
//      public Builder setEmil(
//          java.lang.String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//
//        emil_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string emil = 3;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearEmil() {
//
//        emil_ = getDefaultInstance().getEmil();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>string emil = 3;</code>
//       * @param value The bytes for emil to set.
//       * @return This builder for chaining.
//       */
//      public Builder setEmilBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  checkByteStringIsUtf8(value);
//
//        emil_ = value;
//        onChanged();
//        return this;
//      }
//
//      private java.util.List<PersonMessage.PersonModel.PersonAddress> addresses_ =
//        java.util.Collections.emptyList();
//      private void ensureAddressesIsMutable() {
//        if (!((bitField0_ & 0x00000001) != 0)) {
//          addresses_ = new java.util.ArrayList<PersonMessage.PersonModel.PersonAddress>(addresses_);
//          bitField0_ |= 0x00000001;
//         }
//      }
//
//      private com.google.protobuf.RepeatedFieldBuilderV3<
//          PersonMessage.PersonModel.PersonAddress, PersonMessage.PersonModel.PersonAddress.Builder, PersonMessage.PersonModel.PersonAddressOrBuilder> addressesBuilder_;
//
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public java.util.List<PersonMessage.PersonModel.PersonAddress> getAddressesList() {
//        if (addressesBuilder_ == null) {
//          return java.util.Collections.unmodifiableList(addresses_);
//        } else {
//          return addressesBuilder_.getMessageList();
//        }
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public int getAddressesCount() {
//        if (addressesBuilder_ == null) {
//          return addresses_.size();
//        } else {
//          return addressesBuilder_.getCount();
//        }
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public PersonMessage.PersonModel.PersonAddress getAddresses(int index) {
//        if (addressesBuilder_ == null) {
//          return addresses_.get(index);
//        } else {
//          return addressesBuilder_.getMessage(index);
//        }
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder setAddresses(
//          int index, PersonMessage.PersonModel.PersonAddress value) {
//        if (addressesBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          ensureAddressesIsMutable();
//          addresses_.set(index, value);
//          onChanged();
//        } else {
//          addressesBuilder_.setMessage(index, value);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder setAddresses(
//          int index, PersonMessage.PersonModel.PersonAddress.Builder builderForValue) {
//        if (addressesBuilder_ == null) {
//          ensureAddressesIsMutable();
//          addresses_.set(index, builderForValue.build());
//          onChanged();
//        } else {
//          addressesBuilder_.setMessage(index, builderForValue.build());
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder addAddresses(PersonMessage.PersonModel.PersonAddress value) {
//        if (addressesBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          ensureAddressesIsMutable();
//          addresses_.add(value);
//          onChanged();
//        } else {
//          addressesBuilder_.addMessage(value);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder addAddresses(
//          int index, PersonMessage.PersonModel.PersonAddress value) {
//        if (addressesBuilder_ == null) {
//          if (value == null) {
//            throw new NullPointerException();
//          }
//          ensureAddressesIsMutable();
//          addresses_.add(index, value);
//          onChanged();
//        } else {
//          addressesBuilder_.addMessage(index, value);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder addAddresses(
//          PersonMessage.PersonModel.PersonAddress.Builder builderForValue) {
//        if (addressesBuilder_ == null) {
//          ensureAddressesIsMutable();
//          addresses_.add(builderForValue.build());
//          onChanged();
//        } else {
//          addressesBuilder_.addMessage(builderForValue.build());
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder addAddresses(
//          int index, PersonMessage.PersonModel.PersonAddress.Builder builderForValue) {
//        if (addressesBuilder_ == null) {
//          ensureAddressesIsMutable();
//          addresses_.add(index, builderForValue.build());
//          onChanged();
//        } else {
//          addressesBuilder_.addMessage(index, builderForValue.build());
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder addAllAddresses(
//          java.lang.Iterable<? extends PersonMessage.PersonModel.PersonAddress> values) {
//        if (addressesBuilder_ == null) {
//          ensureAddressesIsMutable();
//          com.google.protobuf.AbstractMessageLite.Builder.addAll(
//              values, addresses_);
//          onChanged();
//        } else {
//          addressesBuilder_.addAllMessages(values);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder clearAddresses() {
//        if (addressesBuilder_ == null) {
//          addresses_ = java.util.Collections.emptyList();
//          bitField0_ = (bitField0_ & ~0x00000001);
//          onChanged();
//        } else {
//          addressesBuilder_.clear();
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public Builder removeAddresses(int index) {
//        if (addressesBuilder_ == null) {
//          ensureAddressesIsMutable();
//          addresses_.remove(index);
//          onChanged();
//        } else {
//          addressesBuilder_.remove(index);
//        }
//        return this;
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public PersonMessage.PersonModel.PersonAddress.Builder getAddressesBuilder(
//          int index) {
//        return getAddressesFieldBuilder().getBuilder(index);
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public PersonMessage.PersonModel.PersonAddressOrBuilder getAddressesOrBuilder(
//          int index) {
//        if (addressesBuilder_ == null) {
//          return addresses_.get(index);  } else {
//          return addressesBuilder_.getMessageOrBuilder(index);
//        }
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public java.util.List<? extends PersonMessage.PersonModel.PersonAddressOrBuilder>
//           getAddressesOrBuilderList() {
//        if (addressesBuilder_ != null) {
//          return addressesBuilder_.getMessageOrBuilderList();
//        } else {
//          return java.util.Collections.unmodifiableList(addresses_);
//        }
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public PersonMessage.PersonModel.PersonAddress.Builder addAddressesBuilder() {
//        return getAddressesFieldBuilder().addBuilder(
//            PersonMessage.PersonModel.PersonAddress.getDefaultInstance());
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public PersonMessage.PersonModel.PersonAddress.Builder addAddressesBuilder(
//          int index) {
//        return getAddressesFieldBuilder().addBuilder(
//            index, PersonMessage.PersonModel.PersonAddress.getDefaultInstance());
//      }
//      /**
//       * <code>repeated .PersonModel.PersonAddress addresses = 4;</code>
//       */
//      public java.util.List<PersonMessage.PersonModel.PersonAddress.Builder>
//           getAddressesBuilderList() {
//        return getAddressesFieldBuilder().getBuilderList();
//      }
//      private com.google.protobuf.RepeatedFieldBuilderV3<
//          PersonMessage.PersonModel.PersonAddress, PersonMessage.PersonModel.PersonAddress.Builder, PersonMessage.PersonModel.PersonAddressOrBuilder>
//          getAddressesFieldBuilder() {
//        if (addressesBuilder_ == null) {
//          addressesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
//              PersonMessage.PersonModel.PersonAddress, PersonMessage.PersonModel.PersonAddress.Builder, PersonMessage.PersonModel.PersonAddressOrBuilder>(
//                  addresses_,
//                  ((bitField0_ & 0x00000001) != 0),
//                  getParentForChildren(),
//                  isClean());
//          addresses_ = null;
//        }
//        return addressesBuilder_;
//      }
//
//      private int gender_ = 0;
//      /**
//       * <code>.Gender gender = 5;</code>
//       * @return The enum numeric value on the wire for gender.
//       */
//      @java.lang.Override public int getGenderValue() {
//        return gender_;
//      }
//      /**
//       * <code>.Gender gender = 5;</code>
//       * @param value The enum numeric value on the wire for gender to set.
//       * @return This builder for chaining.
//       */
//      public Builder setGenderValue(int value) {
//
//        gender_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>.Gender gender = 5;</code>
//       * @return The gender.
//       */
//      @java.lang.Override
//      public PersonMessage.Gender getGender() {
//        @SuppressWarnings("deprecation")
//        PersonMessage.Gender result = PersonMessage.Gender.valueOf(gender_);
//        return result == null ? PersonMessage.Gender.UNRECOGNIZED : result;
//      }
//      /**
//       * <code>.Gender gender = 5;</code>
//       * @param value The gender to set.
//       * @return This builder for chaining.
//       */
//      public Builder setGender(PersonMessage.Gender value) {
//        if (value == null) {
//          throw new NullPointerException();
//        }
//
//        gender_ = value.getNumber();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>.Gender gender = 5;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearGender() {
//
//        gender_ = 0;
//        onChanged();
//        return this;
//      }
//      @java.lang.Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @java.lang.Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:PersonModel)
//    }
//
//    // @@protoc_insertion_point(class_scope:PersonModel)
//    private static final PersonMessage.PersonModel DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new PersonMessage.PersonModel();
//    }
//
//    public static PersonMessage.PersonModel getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static final com.google.protobuf.Parser<PersonModel>
//        PARSER = new com.google.protobuf.AbstractParser<PersonModel>() {
//      @java.lang.Override
//      public PersonModel parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new PersonModel(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<PersonModel> parser() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public com.google.protobuf.Parser<PersonModel> getParserForType() {
//      return PARSER;
//    }
//
//    @java.lang.Override
//    public PersonMessage.PersonModel getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_PersonModel_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_PersonModel_fieldAccessorTable;
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_PersonModel_PersonAddress_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_PersonModel_PersonAddress_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    java.lang.String[] descriptorData = {
//      "\n\014person.proto\"\250\001\n\013PersonModel\022\n\n\002id\030\001 \001" +
//      "(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004emil\030\003 \001(\t\022-\n\taddres" +
//      "ses\030\004 \003(\0132\032.PersonModel.PersonAddress\022\027\n" +
//      "\006gender\030\005 \001(\0162\007.Gender\032)\n\rPersonAddress\022" +
//      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t*\036\n\006Gender\022\010\n\004m" +
//      "ale\020\000\022\n\n\006female\020\001B-\n\034fink02.stream.typei" +
//      "nfo.modelB\rPersonMessageb\006proto3"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_PersonModel_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_PersonModel_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_PersonModel_descriptor,
//        new java.lang.String[] { "Id", "Name", "Emil", "Addresses", "Gender", });
//    internal_static_PersonModel_PersonAddress_descriptor =
//      internal_static_PersonModel_descriptor.getNestedTypes().get(0);
//    internal_static_PersonModel_PersonAddress_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_PersonModel_PersonAddress_descriptor,
//        new java.lang.String[] { "Id", "Name", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
