// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: outer.proto

package fink02.typeinfo.model;

public final class OuterMessage {
  private OuterMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OuterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Outer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    java.util.List<OuterMessage.Outer.Inner>
        getInnerList();
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    OuterMessage.Outer.Inner getInner(int index);
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    int getInnerCount();
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    java.util.List<? extends OuterMessage.Outer.InnerOrBuilder>
        getInnerOrBuilderList();
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    OuterMessage.Outer.InnerOrBuilder getInnerOrBuilder(
        int index);

    /**
     * <code>repeated int32 foo = 3;</code>
     * @return A list containing the foo.
     */
    java.util.List<java.lang.Integer> getFooList();
    /**
     * <code>repeated int32 foo = 3;</code>
     * @return The count of foo.
     */
    int getFooCount();
    /**
     * <code>repeated int32 foo = 3;</code>
     * @param index The index of the element to return.
     * @return The foo at the given index.
     */
    int getFoo(int index);
  }
  /**
   * <pre>
   * https://developers.google.cn/protocol-buffers/docs/proto3
   * </pre>
   *
   * Protobuf type {@code Outer}
   */
  public static final class Outer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Outer)
      OuterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Outer.newBuilder() to construct.
    private Outer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Outer() {
      inner_ = java.util.Collections.emptyList();
      foo_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Outer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Outer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                inner_ = new java.util.ArrayList<OuterMessage.Outer.Inner>();
                mutable_bitField0_ |= 0x00000001;
              }
              inner_.add(
                  input.readMessage(OuterMessage.Outer.Inner.parser(), extensionRegistry));
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                foo_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              foo_.addInt(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                foo_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                foo_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          inner_ = java.util.Collections.unmodifiableList(inner_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          foo_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OuterMessage.internal_static_Outer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OuterMessage.internal_static_Outer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OuterMessage.Outer.class, OuterMessage.Outer.Builder.class);
    }

    public interface InnerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Outer.Inner)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      int getId();
    }
    /**
     * Protobuf type {@code Outer.Inner}
     */
    public static final class Inner extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Outer.Inner)
        InnerOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Inner.newBuilder() to construct.
      private Inner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Inner() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Inner();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Inner(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OuterMessage.internal_static_Outer_Inner_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OuterMessage.internal_static_Outer_Inner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OuterMessage.Outer.Inner.class, OuterMessage.Outer.Inner.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof OuterMessage.Outer.Inner)) {
          return super.equals(obj);
        }
        OuterMessage.Outer.Inner other = (OuterMessage.Outer.Inner) obj;

        if (getId()
            != other.getId()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static OuterMessage.Outer.Inner parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static OuterMessage.Outer.Inner parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static OuterMessage.Outer.Inner parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static OuterMessage.Outer.Inner parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static OuterMessage.Outer.Inner parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static OuterMessage.Outer.Inner parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(OuterMessage.Outer.Inner prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Outer.Inner}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Outer.Inner)
          OuterMessage.Outer.InnerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return OuterMessage.internal_static_Outer_Inner_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return OuterMessage.internal_static_Outer_Inner_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  OuterMessage.Outer.Inner.class, OuterMessage.Outer.Inner.Builder.class);
        }

        // Construct using fink02.stream.typeinfo.model.OuterMessage.Outer.Inner.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return OuterMessage.internal_static_Outer_Inner_descriptor;
        }

        @java.lang.Override
        public OuterMessage.Outer.Inner getDefaultInstanceForType() {
          return OuterMessage.Outer.Inner.getDefaultInstance();
        }

        @java.lang.Override
        public OuterMessage.Outer.Inner build() {
          OuterMessage.Outer.Inner result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public OuterMessage.Outer.Inner buildPartial() {
          OuterMessage.Outer.Inner result = new OuterMessage.Outer.Inner(this);
          result.id_ = id_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof OuterMessage.Outer.Inner) {
            return mergeFrom((OuterMessage.Outer.Inner)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(OuterMessage.Outer.Inner other) {
          if (other == OuterMessage.Outer.Inner.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          OuterMessage.Outer.Inner parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (OuterMessage.Outer.Inner) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Outer.Inner)
      }

      // @@protoc_insertion_point(class_scope:Outer.Inner)
      private static final OuterMessage.Outer.Inner DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new OuterMessage.Outer.Inner();
      }

      public static OuterMessage.Outer.Inner getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Inner>
          PARSER = new com.google.protobuf.AbstractParser<Inner>() {
        @java.lang.Override
        public Inner parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Inner(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Inner> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Inner> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public OuterMessage.Outer.Inner getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int INNER_FIELD_NUMBER = 2;
    private java.util.List<OuterMessage.Outer.Inner> inner_;
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    @java.lang.Override
    public java.util.List<OuterMessage.Outer.Inner> getInnerList() {
      return inner_;
    }
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends OuterMessage.Outer.InnerOrBuilder>
        getInnerOrBuilderList() {
      return inner_;
    }
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    @java.lang.Override
    public int getInnerCount() {
      return inner_.size();
    }
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    @java.lang.Override
    public OuterMessage.Outer.Inner getInner(int index) {
      return inner_.get(index);
    }
    /**
     * <code>repeated .Outer.Inner inner = 2;</code>
     */
    @java.lang.Override
    public OuterMessage.Outer.InnerOrBuilder getInnerOrBuilder(
        int index) {
      return inner_.get(index);
    }

    public static final int FOO_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList foo_;
    /**
     * <code>repeated int32 foo = 3;</code>
     * @return A list containing the foo.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getFooList() {
      return foo_;
    }
    /**
     * <code>repeated int32 foo = 3;</code>
     * @return The count of foo.
     */
    public int getFooCount() {
      return foo_.size();
    }
    /**
     * <code>repeated int32 foo = 3;</code>
     * @param index The index of the element to return.
     * @return The foo at the given index.
     */
    public int getFoo(int index) {
      return foo_.getInt(index);
    }
    private int fooMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < inner_.size(); i++) {
        output.writeMessage(2, inner_.get(i));
      }
      if (getFooList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(fooMemoizedSerializedSize);
      }
      for (int i = 0; i < foo_.size(); i++) {
        output.writeInt32NoTag(foo_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < inner_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, inner_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < foo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(foo_.getInt(i));
        }
        size += dataSize;
        if (!getFooList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        fooMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OuterMessage.Outer)) {
        return super.equals(obj);
      }
      OuterMessage.Outer other = (OuterMessage.Outer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getInnerList()
          .equals(other.getInnerList())) return false;
      if (!getFooList()
          .equals(other.getFooList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getInnerCount() > 0) {
        hash = (37 * hash) + INNER_FIELD_NUMBER;
        hash = (53 * hash) + getInnerList().hashCode();
      }
      if (getFooCount() > 0) {
        hash = (37 * hash) + FOO_FIELD_NUMBER;
        hash = (53 * hash) + getFooList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OuterMessage.Outer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterMessage.Outer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterMessage.Outer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterMessage.Outer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterMessage.Outer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OuterMessage.Outer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OuterMessage.Outer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OuterMessage.Outer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OuterMessage.Outer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OuterMessage.Outer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OuterMessage.Outer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OuterMessage.Outer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OuterMessage.Outer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * https://developers.google.cn/protocol-buffers/docs/proto3
     * </pre>
     *
     * Protobuf type {@code Outer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Outer)
        OuterMessage.OuterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OuterMessage.internal_static_Outer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OuterMessage.internal_static_Outer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OuterMessage.Outer.class, OuterMessage.Outer.Builder.class);
      }

      // Construct using fink02.stream.typeinfo.model.OuterMessage.Outer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInnerFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (innerBuilder_ == null) {
          inner_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          innerBuilder_.clear();
        }
        foo_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OuterMessage.internal_static_Outer_descriptor;
      }

      @java.lang.Override
      public OuterMessage.Outer getDefaultInstanceForType() {
        return OuterMessage.Outer.getDefaultInstance();
      }

      @java.lang.Override
      public OuterMessage.Outer build() {
        OuterMessage.Outer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OuterMessage.Outer buildPartial() {
        OuterMessage.Outer result = new OuterMessage.Outer(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        if (innerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            inner_ = java.util.Collections.unmodifiableList(inner_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.inner_ = inner_;
        } else {
          result.inner_ = innerBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          foo_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.foo_ = foo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OuterMessage.Outer) {
          return mergeFrom((OuterMessage.Outer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OuterMessage.Outer other) {
        if (other == OuterMessage.Outer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (innerBuilder_ == null) {
          if (!other.inner_.isEmpty()) {
            if (inner_.isEmpty()) {
              inner_ = other.inner_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInnerIsMutable();
              inner_.addAll(other.inner_);
            }
            onChanged();
          }
        } else {
          if (!other.inner_.isEmpty()) {
            if (innerBuilder_.isEmpty()) {
              innerBuilder_.dispose();
              innerBuilder_ = null;
              inner_ = other.inner_;
              bitField0_ = (bitField0_ & ~0x00000001);
              innerBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInnerFieldBuilder() : null;
            } else {
              innerBuilder_.addAllMessages(other.inner_);
            }
          }
        }
        if (!other.foo_.isEmpty()) {
          if (foo_.isEmpty()) {
            foo_ = other.foo_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFooIsMutable();
            foo_.addAll(other.foo_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OuterMessage.Outer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OuterMessage.Outer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<OuterMessage.Outer.Inner> inner_ =
        java.util.Collections.emptyList();
      private void ensureInnerIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          inner_ = new java.util.ArrayList<OuterMessage.Outer.Inner>(inner_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          OuterMessage.Outer.Inner, OuterMessage.Outer.Inner.Builder, OuterMessage.Outer.InnerOrBuilder> innerBuilder_;

      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public java.util.List<OuterMessage.Outer.Inner> getInnerList() {
        if (innerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inner_);
        } else {
          return innerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public int getInnerCount() {
        if (innerBuilder_ == null) {
          return inner_.size();
        } else {
          return innerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public OuterMessage.Outer.Inner getInner(int index) {
        if (innerBuilder_ == null) {
          return inner_.get(index);
        } else {
          return innerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder setInner(
          int index, OuterMessage.Outer.Inner value) {
        if (innerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerIsMutable();
          inner_.set(index, value);
          onChanged();
        } else {
          innerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder setInner(
          int index, OuterMessage.Outer.Inner.Builder builderForValue) {
        if (innerBuilder_ == null) {
          ensureInnerIsMutable();
          inner_.set(index, builderForValue.build());
          onChanged();
        } else {
          innerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder addInner(OuterMessage.Outer.Inner value) {
        if (innerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerIsMutable();
          inner_.add(value);
          onChanged();
        } else {
          innerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder addInner(
          int index, OuterMessage.Outer.Inner value) {
        if (innerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerIsMutable();
          inner_.add(index, value);
          onChanged();
        } else {
          innerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder addInner(
          OuterMessage.Outer.Inner.Builder builderForValue) {
        if (innerBuilder_ == null) {
          ensureInnerIsMutable();
          inner_.add(builderForValue.build());
          onChanged();
        } else {
          innerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder addInner(
          int index, OuterMessage.Outer.Inner.Builder builderForValue) {
        if (innerBuilder_ == null) {
          ensureInnerIsMutable();
          inner_.add(index, builderForValue.build());
          onChanged();
        } else {
          innerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder addAllInner(
          java.lang.Iterable<? extends OuterMessage.Outer.Inner> values) {
        if (innerBuilder_ == null) {
          ensureInnerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, inner_);
          onChanged();
        } else {
          innerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder clearInner() {
        if (innerBuilder_ == null) {
          inner_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          innerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public Builder removeInner(int index) {
        if (innerBuilder_ == null) {
          ensureInnerIsMutable();
          inner_.remove(index);
          onChanged();
        } else {
          innerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public OuterMessage.Outer.Inner.Builder getInnerBuilder(
          int index) {
        return getInnerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public OuterMessage.Outer.InnerOrBuilder getInnerOrBuilder(
          int index) {
        if (innerBuilder_ == null) {
          return inner_.get(index);  } else {
          return innerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public java.util.List<? extends OuterMessage.Outer.InnerOrBuilder>
           getInnerOrBuilderList() {
        if (innerBuilder_ != null) {
          return innerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inner_);
        }
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public OuterMessage.Outer.Inner.Builder addInnerBuilder() {
        return getInnerFieldBuilder().addBuilder(
            OuterMessage.Outer.Inner.getDefaultInstance());
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public OuterMessage.Outer.Inner.Builder addInnerBuilder(
          int index) {
        return getInnerFieldBuilder().addBuilder(
            index, OuterMessage.Outer.Inner.getDefaultInstance());
      }
      /**
       * <code>repeated .Outer.Inner inner = 2;</code>
       */
      public java.util.List<OuterMessage.Outer.Inner.Builder>
           getInnerBuilderList() {
        return getInnerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          OuterMessage.Outer.Inner, OuterMessage.Outer.Inner.Builder, OuterMessage.Outer.InnerOrBuilder>
          getInnerFieldBuilder() {
        if (innerBuilder_ == null) {
          innerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              OuterMessage.Outer.Inner, OuterMessage.Outer.Inner.Builder, OuterMessage.Outer.InnerOrBuilder>(
                  inner_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        return innerBuilder_;
      }

      private com.google.protobuf.Internal.IntList foo_ = emptyIntList();
      private void ensureFooIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          foo_ = mutableCopy(foo_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @return A list containing the foo.
       */
      public java.util.List<java.lang.Integer>
          getFooList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(foo_) : foo_;
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @return The count of foo.
       */
      public int getFooCount() {
        return foo_.size();
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @param index The index of the element to return.
       * @return The foo at the given index.
       */
      public int getFoo(int index) {
        return foo_.getInt(index);
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @param index The index to set the value at.
       * @param value The foo to set.
       * @return This builder for chaining.
       */
      public Builder setFoo(
          int index, int value) {
        ensureFooIsMutable();
        foo_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @param value The foo to add.
       * @return This builder for chaining.
       */
      public Builder addFoo(int value) {
        ensureFooIsMutable();
        foo_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @param values The foo to add.
       * @return This builder for chaining.
       */
      public Builder addAllFoo(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFooIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, foo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 foo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFoo() {
        foo_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Outer)
    }

    // @@protoc_insertion_point(class_scope:Outer)
    private static final OuterMessage.Outer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OuterMessage.Outer();
    }

    public static OuterMessage.Outer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Outer>
        PARSER = new com.google.protobuf.AbstractParser<Outer>() {
      @java.lang.Override
      public Outer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Outer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Outer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Outer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OuterMessage.Outer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Outer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Outer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Outer_Inner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Outer_Inner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013outer.proto\"R\n\005Outer\022\n\n\002id\030\001 \001(\005\022\033\n\005in" +
      "ner\030\002 \003(\0132\014.Outer.Inner\022\013\n\003foo\030\003 \003(\005\032\023\n\005" +
      "Inner\022\n\n\002id\030\001 \001(\005B,\n\034fink02.stream.typei" +
      "nfo.modelB\014OuterMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Outer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Outer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Outer_descriptor,
        new java.lang.String[] { "Id", "Inner", "Foo", });
    internal_static_Outer_Inner_descriptor =
      internal_static_Outer_descriptor.getNestedTypes().get(0);
    internal_static_Outer_Inner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Outer_Inner_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
